management:
  health:
    ldap:
      enabled: false
  endpoints:
    web:
      exposure:
        include: httptrace,health
logging:
  level:
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
    com.consdata.kouncil: DEBUG
    org.apache.kafka.clients: WARN
    org.apache.kafka.clients.NetworkClient: INFO
    org.apache.kafka.common.utils.AppInfoParser: WARN
kouncil:
  auth:
    active-provider: inmemory # inmemory, ldap, ad, sso
    ldap:
      provider-url: "ldaps://kouncil.io"
      search-base: "OU=Users,DC=kouncil,DC=io"
      search-filter: "(&(objectClass=user)(uid={0})(memberOf=CN=KOUNCIL,CN=Users,DC=kouncil,DC=io))"
      group-search-base: "ou=Groups,DC=kouncil,DC=io"
      group-search-filter: "(memberuid={0})"
      group-role-attribute: "cn"
    ad:
      domain: "acme.com"
      url: "ldap://acme.com:389"
      search-filter: "(&(objectClass=user)(userPrincipalName={0})(memberOf=CN=KOUNCIL,CN=Users,DC=kouncil,DC=io))"
    sso:
      supported:
        providers: github
  topics:
    exclude-regex-patterns: __.*
  authorization:
    role-admin: admin_group
    role-editor: editor_group
    role-viewer: viewer_group
  survey:
    base-path: "https://kouncil-eximee-survey-n22nwdfueq-lm.a.run.app/kouncil"

spring:
  datasource:
  jpa:
    show-sql: true
    hibernate:
      default_schema: KOUNCIL
  flyway:
    enabled: true
