export enum SystemFunctionName {

  TOPIC_LIST = 'TOPIC_LIST',
  TOPIC_CREATE = 'TOPIC_CREATE',
  TOPIC_UPDATE = 'TOPIC_UPDATE',
  TOPIC_DELETE = 'TOPIC_DELETE',
  TOPIC_MESSAGES = 'TOPIC_MESSAGES',
  TOPIC_SEND_MESSAGE = 'TOPIC_SEND_MESSAGE',
  TOPIC_RESEND_MESSAGE = 'TOPIC_RESEND_MESSAGE',

  BROKERS_LIST = 'BROKERS_LIST',
  BROKER_DETAILS = 'BROKER_DETAILS',

  CONSUMER_GROUP_LIST = 'CONSUMER_GROUP_LIST',
  CONSUMER_GROUP_DELETE = 'CONSUMER_GROUP_DELETE',
  CONSUMER_GROUP_DETAILS = 'CONSUMER_GROUP_DETAILS',

  TRACK_LIST = 'TRACK_LIST',

  SCHEMA_LIST = 'SCHEMA_LIST',
  SCHEMA_DETAILS = 'SCHEMA_DETAILS',
  SCHEMA_CREATE = 'SCHEMA_CREATE',
  SCHEMA_UPDATE = 'SCHEMA_UPDATE',
  SCHEMA_DELETE = 'SCHEMA_DELETE',

  LOGIN = 'LOGIN',
  USER_GROUPS = 'USER_GROUPS',
  USER_GROUPS_LIST = 'USER_GROUPS_LIST',
  USER_GROUP_CREATE = 'USER_GROUP_CREATE',
  USER_GROUP_UPDATE = 'USER_GROUP_UPDATE',
  USER_GROUP_DELETE = 'USER_GROUP_DELETE',

  CLUSTER_LIST = 'CLUSTER_LIST',
  CLUSTER_CREATE = 'CLUSTER_CREATE',
  CLUSTER_UPDATE = 'CLUSTER_UPDATE',
  CLUSTER_DETAILS = 'CLUSTER_DETAILS',
  CLUSTER_DELETE = 'CLUSTER_DELETE',

  POLICY_LIST = 'POLICY_LIST',
  POLICY_CREATE = 'POLICY_CREATE',
  POLICY_DETAILS = 'POLICY_DETAILS',
  POLICY_UPDATE = 'POLICY_UPDATE',
  POLICY_DELETE = 'POLICY_DELETE'

}
