name: Build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v2
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
      - name: Build Project and Image
        run: ./mvnw package -P dist
      - name: Set version env variable
        run: |
          echo "MVN_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
         username: ${{ secrets.DOCKERHUB_USERNAME }}
         password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push to Docker
        run: docker push "consdata/kouncil:${{ env.MVN_VERSION }}"
      - name: Tag Latest Snapshot
        run: docker tag "consdata/kouncil:${{ env.MVN_VERSION }}" "consdata/kouncil:latest_snapshot"
      - name: Push to Docker
        run: docker push "consdata/kouncil:latest_snapshot"
